version: "2.1"

services:
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - 22181:2181
    networks:
      - local

  kafka:
    image: confluentinc/cp-kafka:latest
    depends_on:
      - zookeeper
    ports:
      - 29092:29092
    healthcheck:
      test: curl -sS http://kafka:9092 || exit 1
      interval: 5s
      timeout: 10s
      retries: 5
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    networks:
      - local

  producer:
    depends_on:
      - zookeeper
      - kafka

    build: /home/antonshubin/GolandProjects/ProductsGenerator
    ports:
      - 9090:9090
    networks:
      - local

    environment:
      ZADDRES: kafka

#  consumer:
#    depends_on:
#      - zookeeper
#      - kafka
#      - producer
#
#    ports:
#      - 9091:9091
#
#    build: /home/antonshubin/GolandProjects/Kafka-pong
#    networks:
#      - local
#
#    environment:
#      ZADDRES: kafka

networks:
  local:
    driver: bridge